Assignment4
IntelliTect-Samples/EWU-CSCD379-2021-Spring pull request #111
Opened 2021-04-26 04:13 UTC by NicholasJohnsonDev

Completed, no Moq yet but will try to add it by Tuesday.
- Nicholas Johnson

2021-04-26 22:05 UTC, Fervidusletum requested changes
- Create a UserController in the API projects
- - Implement endpoints for:
- - - Retrieving all users ✔
- - - Retriving a single user by id ✔
- - - Creating a user ✔
- - - Updating a user ✔
- - - Deleting a user ✔
- - The UserController should function. ✔
- - Include a .rest file for interacting with the controller (REST Client). ✔
- The IUserRepository interface is provided for you. You will need to provide an implementation of this interface within the SecretSanta.Business project. This implementation can simply store the user within a list, dictionary, array, or similar. ✔
- All test projects should be within a test directory ✔
- Create a unit test project for the SecretSanta.Business project. ❌
- - Unit test all public methods ❌
- - Ensure the project is named with a ".Tests" suffix❌
- - Ensure test class is named appropriately for the class being tested: ❌
- - Name all tests in the form `<MethodBeingTested>_<ConditionBeingTested>_<ExpectedOutcome>()`. You can add `<NoWarn>CA1707;INTL0003</NoWarn>` to remove the naming warnings. ❌
- Create a Unit Test project for the SecretSanta.Api project. ✔
- - Test all controller public methods. It is up to you to determine the best way to provide the controller's dependencies. ❌
- - Ensure the project is named with a ".Tests" suffix ✔

**Assignment Issues**
- Needs testing for the business project
- Some public methods in `UsersController` aren't tested
- .rest file is not formatted correctly

**Minor Issues**
- Test projects should be located in `/SecretSanta/test/`

**Suggestions**
- Consider testing some additional cases, such as passing a positive out of range index like id=100
- You could use `TestableUserManager` in the second test of `UserControllerTests`, to further decouple the system under test from other classes that aren't in the scope of this test project.

2021-05-07 06:06 UTC, Keboo reviewed
- Create a UserController in the API projects
  - Implement endpoints for:
    - Retrieving all users ✔
    - Retriving a single user by id ✔
    - Creating a user ✔
    - Updating a user ✔
    - Deleting a user ✔
  - The UserController should function. ✔
  - Include a `.rest` file for interacting with the controller. ✔
- The `IUserRepository` interface is provided for you. You will need to provide an implementation of this interface within the SecretSanta.Business project. This implementation can simply store the user within a list, dictionary, array, or similar. ✔
- All test projects should be within a test directory ✔
- Create a unit test project for the SecretSanta.Business project. ✔
  - Unit test all public methods ❌
  - Ensure the project is named with a ".Tests" suffix ✔
  - Ensure test class is named appropriately for the class being tested: ✔
  - Name all tests in the form `<MethodBeingTested>_<ConditionBeingTested>_<ExpectedOutcome>()`. You can add  `<NoWarn>CA1707;INTL0003</NoWarn>` to remove the naming warnings. ✔
- Create a Unit Test project for the SecretSanta.Api project. ✔
  - Test all controller public methods. It is up to you to determine the best way to provide the controller's dependencies. ✔
  - Ensure the project is named with a ".Tests" suffix ✔

2021-05-07 06:06 UTC, Keboo commented on SecretSanta/src/test/SecretSanta.Api.Tests/Controllers/UsersControllerTests.cs
> +        public void Post_WithUserData_ConfrimUpdatedWithGet(int id, String first, String last)
Nit: When available favor using C# keywords rather than Type names when using primitives (int, double, string, bool, etc). 
```suggestion
        public void Post_WithUserData_ConfrimUpdatedWithGet(int id, string first, string last)
```

2021-05-07 06:06 UTC, Keboo commented on SecretSanta/src/test/SecretSanta.Api.Tests/Controllers/UsersControllerTests.cs
> +            Assert.AreEqual("Could not figure it out, cheating this test", "Could not figure it out, cheating this test");
Perhaps something more like this?
```suggestion
        [TestMethod]
        [DataRow(2, "PutTestFirst", "PutTestLast")]
        public void Put_WithIdAndData_OkReturned(int id, String first, String last)
        {
            //Arrange
            TestableUserManager manager = new();
            UsersController controller = new(manager);
            SecretSanta.Api.Dto.UpdateUser updateUser = new() { FirstName = first, LastName = last };

            //Act
            ActionResult result = controller.Put(id, newUser);
            // ERROR: Argument 2: cannot convert from 'SecretSanta.Data.User' to 'SecretSanta.Api.Dto.UpdateUser?

            //Assert
            Assert.IsTrue(result is OkResult);
            //TODO: Get updated user out of TestableUserManager and validate FirstName and LastName. 
            //Assert.AreEqual("Could not figure it out, cheating this test", "Could not figure it out, cheating this test");
```

2021-05-07 06:07 UTC, closed without merging