Assignment5 (WIP)
IntelliTect-Samples/EWU-CSCD379-2021-Spring pull request #122
Opened 2021-05-03 00:26 UTC by Cybotive

2021-05-03 21:50 UTC, Fervidusletum requested changes
- Update the API project with the following
- - Add a new Dto namespace ✔
- - The UserController should only accept or return classes from the Dto namespace. Create any needed classes there and update the controller to use them. You will need to convert between the DTO classes and the relevant entities as needed. ✔
- - Add OpenAPI (swagger) endpoint ✔
- - Use the OpenAPI to generate a C# client with relevant interfaces ✔
- - Decorate all relevant API endpoints in the UserController with the appropriate ProducesResponseType ✔
- Update the Web project with the following
- - Register the generated UserClients class using its interface with the Dependency Injection (DI) service. ✔
- - Update the UserController to take in the generated client as a dependency. ✔
- - Convert the UserController from using the MockData to using the client to get data from the API service. ✔
- - Update the controller to convert back and forth between the ViewModel classes and the API DTO classes as needed. ✔
- Update the SecretSanta.Api.Tests with the following:
- - The controller tests should be interation tests not unit tests. ✔
- - All endpoints should be tested. ❌
- - The UserController should use a test double for the IUserRepository to avoid needing to retest business and data logic. ✔
- Create a new SecretSanta.Web.Tests projecs with the following:
- - It should be inside of the test directory. ✔
- - It should have nullable reference types enabled. ✔
- - It should have functional tests for all endpoints in the UserController that access the API. ❌
- - It should use a test double for the API service. This test double should be used to validate the controller's interaction with the API without actually calling the API. ✔
- Extra Credit:
- - Rather than coping data between view models and DTOs, and DTOs and entities; use AutoMapper to handle it for you. ❌


Looks good for the most part!  Just some more endpoint testing in both api and web userscontroller to do.

2021-05-03 21:50 UTC, Fervidusletum commented on SecretSanta/src/SecretSanta.Api/Controllers/UsersController.cs
> +        public IEnumerable<FullUser> Get()
Line 22 doesn't match the return type of the function (`user`, should be `fulluser`)

2021-05-03 22:06 UTC, Fervidusletum commented
Found a new issue: when running the client + server, clicking on a user to edit will generate an exception.
`InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[SecretSanta.Web.Api.FullUser,SecretSanta.Web.Api.UsersClient+<GetAsync>d__15]', but this ViewDataDictionary instance requires a model item of type 'SecretSanta.Web.ViewModels.UserViewModel'.`

2021-05-04 01:58 UTC, Cybotive commented on SecretSanta/src/SecretSanta.Api/Controllers/UsersController.cs
> +        public IEnumerable<FullUser> Get()
I didn't know exactly what the server would respond with so I changed it back to User but you're likely right.

2021-05-04 02:01 UTC, Cybotive commented
> 
> 
> Found a new issue: when running the client + server, clicking on a user to edit will generate an exception.
> `InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder1+AsyncStateMachineBox1[SecretSanta.Web.Api.FullUser,SecretSanta.Web.Api.UsersClient+<GetAsync>d__15]', but this ViewDataDictionary instance requires a model item of type 'SecretSanta.Web.ViewModels.UserViewModel'.`

Did you run `npm run build:dev` first? Could be a valid error but I suspect that would fix it.

2021-05-09 04:21 UTC, Keboo reviewed
- Update the API project with the following
  - Add a new Dto namespace ✔
  - The `UserController` should only accept or return classes from the Dto namespace. Create any needed classes there and update the controller to use them. You will need to convert between the DTO classes and the relevant entities as needed. ✔
  - Add OpenAPI (swagger) endpoint ✔
  - Use the OpenAPI to generate a C# client with relevant interfaces ✔
  - Decorate all relevant API endpoints in the `UserController` with the appropriate [ProducesResponseType](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-5.0#iactionresult-type) ✔
- Update the Web project with the following
  - Register the generated `UserClients` class using its interface with the Dependency Injection (DI) service. ✔
  - Update the `UserController` to take in the generated client as a dependency. ✔
  - Convert the `UserController` from using the `MockData` to using the client to get data from the API service. ✔
  - Update the controller to convert back and forth between the ViewModel classes and the API DTO classes as needed. ✔
- Update the SecretSanta.Api.Tests with the following:
  - The controller tests should be [interation tests](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0) not unit tests. ✔
  - All endpoints should be tested. ✔
  - The `UserController` should use a test double for the `IUserRepository` to avoid needing to retest business and data logic. ✔
- Create a new SecretSanta.Web.Tests projecs with the following:
  - It should be inside of the test directory. ✔
  - It should have nullable reference types enabled. ✔
  - It should have functional tests for all endpoints in the `UserController` that access the API. ✔
  - It should use a test double for the API service. This test double should be used to validate the controller's interaction with the API without actually calling the API. ✔

2021-05-09 04:21 UTC, Keboo commented on SecretSanta/src/SecretSanta.Api/Controllers/UsersController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)] // Doesn't happen in this implementation
Since it doesn't happen it can be omitted.
```suggestion
```

2021-05-09 04:21 UTC, Keboo commented on SecretSanta/test/SecretSanta.Api.Tests/Controllers/UserControllerTests.cs
> +        }
In general you don't need to test this case as it will be covered by your other tests.

2021-05-09 04:21 UTC, Keboo commented on SecretSanta/test/SecretSanta.Api.Tests/Controllers/UserControllerTests.cs
> +            }
Typically you want to avoid any conditional statements in your tests like this. A better way to handle this case would be to simply assert that the `userList` is not null.
```suggestion
            Assert.IsNotNull(userList);
```

2021-05-09 04:21 UTC, closed without merging