Assignment8
IntelliTect-Samples/EWU-CSCD379-2021-Spring pull request #187
Opened 2021-05-24 04:43 UTC by NicholasJohnsonDev

It's not letting push up changes right now. Posted the for help in Teams with screenshot.

2021-05-24 19:46 UTC, NicholasJohnsonDev commented
Currently working on this, should be done by 2pm

2021-05-25 02:24 UTC, Fervidusletum commented
Reviewing

2021-05-25 03:00 UTC, Fervidusletum requested changes
## Assignment
- Update the `GroupRepository` with functionality to generate gift assignments. ✔
  - A group with with 2 or fewer users should result in an error. This error should be displayed to a user. ✔
  - A user is not allowed to be both the Giver and Recipient of the assignment. ✔
- Update the GroupsController with an endpoint for generating the assignments. ✔
- Update the Groups/Edit page to contain the UI elements for the following
  - A means to generate assignments. ✔
  - A means to display any errors that occurs while generating assignments. ✔
  - Display of the assignments for each of the users. ✔
- Write appropriate unit tests for changes made to the `GroupRepository` ✔
- Write appropriate functional tests for the change made to the `GroupsController` ❌

## Extra Credit
- There is currently no way to for a user to add gifts. On the edit user page add functionality to be able to add a gift to the user. ❌
- Allow for navigating to a user from the Group edit page to make it easy to see the gifts requested by a user. ❌

## Comments
- The GroupRepository GenerateAssignments_WithInvalidId test intermittently fails.
  - I ran into a similar issue; I fixed it by changing the test value from 42 to a unique value.
- Both GroupController tests for CreateAssignments are failing.
  - WithError expects a badrequest, but gets a notfound.
  - WithSuccess expects an OK but gets a notfound.
- GenerateAssignments isn't tested with regard to ordering of generated assignments.
- While the alert works for displaying errors, it's rather annoying. IMO it would be better to display the error in-line on the page.

2021-05-30 06:29 UTC, Keboo reviewed
# Assignment
- Update the `GroupRepository` with functionality to generate gift assignments. ✔
  - A group with with 2 or fewer users should result in an error. This error should be displayed to a user. ✔
  - A user is not allowed to be both the Giver and Recipient of the assignment. ✔
- Update the GroupsController with an endpoint for generating the assignments. ✔
- Update the Groups/Edit page to contain the UI elements for the following
  - A means to generate assignments. ✔
  - A means to display any errors that occurs while generating assignments. ✔
  - Display of the assignments for each of the users. ✔
- Write appropriate unit tests for changes made to the `GroupRepository` ✔
- Write appropriate functional tests for the change made to the `GroupsController` ✔

2021-05-30 06:29 UTC, Keboo commented on SecretSanta/src/SecretSanta.Business/GroupRepository.cs
> +                return AssignmentResult.Error("Group Group must have at least three users");
```suggestion
                return AssignmentResult.Error("Group must have at least three users");
```

2021-05-30 06:29 UTC, Keboo commented on SecretSanta/test/SecretSanta.Business.Tests/GroupRepositoryTests.cs
> +        public void GenerateAssignments_WithInvalidId_CreatesAssignments()
```suggestion
        public void GenerateAssignments_WithInvalidId_ReturnsNotFoundError()
```

2021-05-30 06:33 UTC, Keboo commented
# Assignment
- Update the `GroupRepository` with functionality to generate gift assignments. ✔
  - A group with with 2 or fewer users should result in an error. This error should be displayed to a user. ✔
  - A user is not allowed to be both the Giver and Recipient of the assignment. ✔
- Update the GroupsController with an endpoint for generating the assignments. ✔
- Update the Groups/Edit page to contain the UI elements for the following
  - A means to generate assignments. ✔
  - A means to display any errors that occurs while generating assignments. ✔
  - Display of the assignments for each of the users. ✔
- Write appropriate unit tests for changes made to the `GroupRepository` ✔
- Write appropriate functional tests for the change made to the `GroupsController` ✔

2021-05-30 06:34 UTC, closed without merging